import { cars } from "./cars"
import { trips } from "./trips"

export const users = [
    {
        id: 1,
        email: `gclooney97@gmail.com`,
        firstName: 'George',
        lastName: 'Clooney',
        host: false,
        cars: [],
        trips: [trips[0],trips[3],trips[4],],
        
    },
    {
        id: 2,
        email: `byoon97@gmail.com`,
        firstName: 'B',
        lastName: 'Yoon',
        host: true,
        cars: [cars[0], cars[1], cars[2], cars[3]],
        trips: [],    
    },
    {
        id: 3,
        email: `TINAfEY5@gmail.com`,
        firstName: 'Tina',
        lastName: 'Fey',
        host: false,
        cars: [],
        trips: [trips[1],trips[5],trips[7],],
    },
    {
        id: 4,
        email: `Graceg96.com`,
        firstName: 'Grace',
        lastName: 'Gong',
        host: true,
        cars: [cars[4], cars[5], cars[9]],
        trips: [],    
    },
    {
        id: 5,
        email: `Christineg@gmail.com`,
        firstName: 'Christine',
        lastName: 'Gong',
        host: true,
        cars: [cars[6], cars[7], cars[8]],
        trips: [],    
    },
    {
        id: 6,
        email: `ericholmes@gmail.com`,
        firstName: 'Eric',
        lastName: 'Holmes',
        host: false,
        cars: [],
        trips: [trips[2],trips[6],trips[11],trips[14],],
    },
    {
        id: 7,
        email: `LebronJames@gmail.com`,
        firstName: 'Lebron',
        lastName: 'James',
        host: false,
        cars: [],
        trips: [trips[8],trips[12],trips[15],trips[21],],
    },
    {
        id: 8,
        email: `djtrump@gmail.com`,
        firstName: 'Donald',
        lastName: 'Trump',
        host: false,
        cars: [],
        trips: [trips[9],trips[13],trips[16],trips[17],],
    },
    {
        id: 9,
        email: `Razerhead@gmail.com`,
        firstName: 'Nick',
        lastName: 'James',
        host: false,
        cars: [],
        trips: [trips[10],trips[18],trips[22],],
    },
    {
        id: 10,
        email: `alfredjones@gmail.com`,
        firstName: 'Alfred',
        lastName: 'Jones',
        host: false,
        cars: [],
        trips: [trips[19],],
    },
    {
        id: 11,
        email: `StacyKee@gmail.com`,
        firstName: 'Stacy',
        lastName: 'Kee',
        host: false,
        cars: [],
        trips: [trips[20],],
    },
]

export const userTripsMapping: Record<number, number[]> = {
    0: [0, 3, 4],
    2: [1, 5, 7],
    6: [8, 12, 15, 21],
    7: [9, 13, 16, 17],
    8: [10, 18, 22],
    9: [19],
    10: [20]
  };
